#!/usr/bin/env python3

import os
import sys
import signal
import time
def main():
  while True:
    time.sleep(10)
    os.system('npm start')

def signal_handler(signal, frame):
  print ('INFO Good Bye')
  sys.exit(0)

assert __name__ == '__main__'

signal.signal(signal.SIGINT, signal_handler)

print ('INFO Judge Node is running. Press Ctrl + C to stop')

main()
