#!/usr/bin/env python3

import os
import sys
import signal
import time
from colorama import Fore, Back, Style

def main():
  while True:
    os.system('npm start')
    time.sleep(10)

def signal_handler(signal, frame):
  print ('\n['+ Fore.GREEN + 'INFO' + Fore.RESET + ']' + ' Good Bye')
  sys.exit(0)

assert __name__ == '__main__'

signal.signal(signal.SIGINT, signal_handler)

print ('['+ Fore.GREEN + 'INFO' + Fore.RESET + '] Judge Node is running. Press Ctrl + C to stop')

main()
